// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package src

import (
	"any/bookingtogo-service/internal/handler"
	"any/bookingtogo-service/internal/repository"
	"any/bookingtogo-service/internal/service"
	"any/bookingtogo-service/src/db"
	"any/bookingtogo-service/src/redis"
)

// Injectors from injector.go:

func InitializeNasionalityController() (handler.NasionalityHandler, error) {
	gormDB := db.GetDB()
	redisClient := redis.NewRedisClient()
	nasionalityRepository := repository.NewNasionalityRepository()
	nasionalityService := service.NewNasionalityService(gormDB, redisClient, nasionalityRepository)
	nasionalityHandler := handler.NewNasionalityHandler(nasionalityService, redisClient)
	return nasionalityHandler, nil
}

func InitializeCustomerController() (handler.CustomerHandler, error) {
	gormDB := db.GetDB()
	redisClient := redis.NewRedisClient()
	customerRepository := repository.NewUserRepository()
	customerService := service.NewCustomerService(gormDB, redisClient, customerRepository)
	customerHandler := handler.NewCustomerHandler(customerService)
	return customerHandler, nil
}
