// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package src

import (
	"any/bookingtogo-service/internal/handler"
	"any/bookingtogo-service/internal/repository"
	"any/bookingtogo-service/internal/service"
	"any/bookingtogo-service/src/db"
	"any/bookingtogo-service/src/redis"
)

// Injectors from injector.go:

func InitializeGlobalConfig() (handler.GlobalConfig, error) {
	gormDB := db.GetDB()
	redisClient := redis.NewRedisClient()
	customerRepository := repository.NewUserRepository()
	customerService := service.NewCustomerService(gormDB, redisClient, customerRepository)
	nasionalityRepository := repository.NewNasionalityRepository()
	nasionalityService := service.NewNasionalityService(gormDB, redisClient, nasionalityRepository)
	globalConfig := handler.NewGlobalHandler(gormDB, redisClient, customerService, nasionalityService, customerRepository, nasionalityRepository)
	return globalConfig, nil
}
